
package parqueaderoclienteescritorio.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webServices", targetNamespace = "http://sercivios/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param cedula
     * @param id
     * @param nombre
     * @param placa
     */
    @WebMethod
    @RequestWrapper(localName = "listarAddorEdit", targetNamespace = "http://sercivios/", className = "parqueaderoclienteescritorio.ws.ListarAddorEdit")
    @ResponseWrapper(localName = "listarAddorEditResponse", targetNamespace = "http://sercivios/", className = "parqueaderoclienteescritorio.ws.ListarAddorEditResponse")
    @Action(input = "http://sercivios/webServices/listarAddorEditRequest", output = "http://sercivios/webServices/listarAddorEditResponse")
    public void listarAddorEdit(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "cedula", targetNamespace = "")
        String cedula,
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @return
     *     returns java.util.List<parqueaderoclienteescritorio.ws.Registro>
     */
    @WebMethod(operationName = "Listar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Listar", targetNamespace = "http://sercivios/", className = "parqueaderoclienteescritorio.ws.Listar")
    @ResponseWrapper(localName = "ListarResponse", targetNamespace = "http://sercivios/", className = "parqueaderoclienteescritorio.ws.ListarResponse")
    @Action(input = "http://sercivios/webServices/ListarRequest", output = "http://sercivios/webServices/ListarResponse")
    public List<Registro> listar();

}
